[build]
  base    = ""
  command = "yarn build"
  functions = "built-lambda"
  publish = "build"

# This a rule for Single Page Applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
